### ISSUE TITLE
DLL not loading on TD

### ISSUE THREAD

**Issue by simplo** [DBraun/TD-FaceCHOP#2]
Hi, first of all thank you fro sharing your work!!
I followed all the instructions and compiled with VS 2019.
So I obtained dlib19.19.99_release_64bit_msvc1925 instead of dlib19.17.99_release_64bit_msvc1921.
Compile of the DLL was ok, but once I open the TD project the cplusplus1 says "fail to load the dll".
Even if I create a new cplusplus CHOP to load the DLL the error is the same, but I have not clue of where is the problem.
My TD version is 20625.
Can you please help me? 
Thank you!

**Comment by simplo** [comment]
Me stupid! Did not copied the other DLL in the same folder.
:D
It works!!! It is fantastic!
Thank you!

**Comment by DBraun** [comment]
Hey sure thanks for trying it out. I've updated the instructions just a bit to make it easier to find/copy `opencv_world411.dll`
